# Generated by Django 2.1.2 on 2018-11-29 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simap_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxLanPort', models.IntegerField()),
                ('maxWanPort', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HardwareInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portName', models.CharField(max_length=50)),
                ('portEquip', models.BooleanField(default=False)),
                ('ifOperStatus', models.BooleanField(default=False)),
                ('ifAdminStatus', models.BooleanField(default=False)),
                ('HardwareField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simap_rest.HardwareField')),
            ],
        ),
        migrations.CreateModel(
            name='Wan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portName', models.CharField(max_length=50)),
                ('portEquip', models.BooleanField(default=False)),
                ('ifOperStatus', models.BooleanField(default=False)),
                ('ifAdminStatus', models.BooleanField(default=False)),
                ('HardwareField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simap_rest.HardwareField')),
            ],
        ),
        migrations.CreateModel(
            name='WifiAnalyzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='hardwarefield',
            name='hardwareInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simap_rest.HardwareInfo'),
        ),
    ]
