# Generated by Django 2.1.2 on 2018-11-29 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simap_rest', '0002_auto_20181129_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultCode', models.IntegerField()),
                ('resultMessage', models.CharField(max_length=50)),
                ('isSuccessful', models.BooleanField(default=True)),
                ('hardwareInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simap_rest.HardwareInfo')),
            ],
        ),
        migrations.DeleteModel(
            name='WifiAnalyzer',
        ),
    ]
