# Generated by Django 2.1.2 on 2018-12-13 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simap_rest', '0004_auto_20181129_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardwarefield',
            name='hardwareInfo',
        ),
        migrations.AddField(
            model_name='hardwareinfo',
            name='hardware_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hardwareInfo', to='simap_rest.HardwareField'),
        ),
        migrations.AlterField(
            model_name='lan',
            name='hardwareField',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lan', to='simap_rest.HardwareField'),
        ),
        migrations.AlterField(
            model_name='wan',
            name='hardwareField',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wan', to='simap_rest.HardwareField'),
        ),
    ]
